  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: grpc-service
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: grpc-server
          Image: your_grpc_server_image
          PortMappings:
            - ContainerPort: 50051
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/grpc-server
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
        - Name: grpc-gateway
          Image: your_grpc_gateway_image
          PortMappings:
            - ContainerPort: 8080
          Essential: true
          Environment:
            - Name: GRPC_SERVER_ADDRESS
              Value: "grpc-server:50051"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/grpc-gateway
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet
          SecurityGroups: 
            - !Ref ECSSecurityGroup
  
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic to gRPC server and Gateway
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0